#########################################################
# Gradle Properties                                     #
#########################################################
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
#########################################################
# Mod Info                                              #
#########################################################
mod_id=maidsoulkitchen
mod_name=Maidsoul Kitchen
mod_license=MIT
mod_version=0.1.5
mod_group_id=com.github.wallev.maidsoulkitchen
mod_authors=Azumic, DemSum
mod_description=Make maid learn more skill.
mod_issue_tracker_url=https://github.com/DemSum/MaidsoulKitchen/issues
mod_credits=MaidsoulKitchen by Azumic; contributions by TartaricAcid, Pajinyi, and lezizijiang2; Touhou Little Maid by TartaricAcid; Sophisticated Storage and Sophisticated Backpacks by P3pp3rF1y; Farmer's Delight by vectorwing; DrinkBeer by Lekavar and MarbleGateKeeper; Kaleidoscope Cookery by YSBB, TartaricAcid, and Azumic; maintained fork by DemSum

mod_update_json_url=
mod_display_url=https://github.com/DemSum/MaidsoulKitchen
mod_logo_file=

